# Generated by Django 3.1.1 on 2020-09-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_auto_20200916_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(),
        ),
    ]
